version: '3.8'
services:
  web:
    build: ./apache-php
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: txori4737
      MYSQL_DATABASE: retail_store
      MYSQL_USER: admin
      MYSQL_PASSWORD: txori4737
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: